### ISSUE TITLE
Last character is removed when clicking the original microflow button

### ISSUE THREAD

**Issue by Mcpoowl** [Finaps/EnterKeyWidget#2]
We have the following setup:
ZipCode + housenumber. Housenumer is the widget, which executes a microflow with progress bar.
When pressing the ENTER key, everything works,

However, when we click the 'Search' button,(Which has the same microflow attached as the widget) instead of pressing enter, the last character is removed from the housenumer:

Example:
Zipcode 1234AB 22 ENTER --> returns 1234AB 22
Zipcode 1234AB 22 MF click --> returns 1234AB 2

**Comment by ChristiaanWestgeest** [comment]
Interesting. I've not witnessed this behavior myself yet. 
Does it occur with a specific browser(version), or across all platforms?

**Comment by Mcpoowl** [comment]
Tested with Chrome and IE11.
Easily tested by placing a widget and a normal textbox with the same attribute directly below. I think the field is updated after each character. Since ENTER is a new action, it completes the field, however, clicking does not update the field.

**Comment by ChristiaanWestgeest** [comment]
You are correct. It seems to be an error that was inadvertently introduced whilst trying to resolve another issue in the latest release.
I think I've resolved the bug. A new release is on the way.

**Comment by Mcpoowl** [comment]
Fixed! Thanks!
